### ISSUE TITLE
dataset download link problem

### ISSUE THREAD

**Issue by zhuxinguang33** [CrystalSixone/PASTS#1]
Thanks for your sharing!
I tried to download annotations, features, and pretrained models of R2R by your link for twice because of the network error. And I wanted to download again, the dropbox told me the link was temporally closed for too much access.
How can I fix it? Thank you very much!

**Comment by CrystalSixone** [comment]
Hello! I have resolved the download limit issue, and the link should now be accessible. Additionally, to provide you with an alternative option, I plan to create a Baidu network disk link in the next few days. Thank you for your reminder and patience :)

**Comment by zhuxinguang33** [comment]
Thank you very much!
